name: Build the docker image

on:
  push:
    branches: [ main ]
  repository_dispatch:
  workflow_dispatch:
    inputs:
      skip_check:
        description: 'Whether to skip the version check'     
        required: true
        default: 'false'
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Disable on Forked Repo
        run: |
          if [[ "$GITHUB_REPOSITORY" != "pansila/v2ray_heroku" ]]; then
            echo "Do not run on a forked repo unless you know what you are doing"
            exit 1
          fi

      - uses: actions/checkout@v2

      - name: Check the latest version
        run: |
          github_latest=$(utils/github_get_latest_release.sh v2fly/v2ray-core)
          docker_latest=$(utils/docker_image_find_tag_equal_to_latest.sh -n pansila/v2ray_heroku -q)
          if [[ "$github_latest" == "$docker_latest" ]]; then
            echo "CANCEL=1" >> $GITHUB_ENV
            echo "docker image is up to date, cancelling the updating..."
            exit 0
          fi
          if [ -z "$github_latest" ] || [ -z "$docker_latest" ]; then
            echo "CANCEL=1" >> $GITHUB_ENV
            echo "Getting the wrong versions: current: $docker_latest, latest: $github_latest, cancelling..."
            exit 0
          fi
          echo "VERSION=$github_latest" >> $GITHUB_ENV
          echo "CANCEL=0" >> $GITHUB_ENV
          echo "docker image is out of date, current: $docker_latest, latest: $github_latest, updating..."

      - uses: actions/github-script@v2
        id: cancel
        with:
          script: |
            const { owner, repo } = context.repo
            if (${{ env.CANCEL }} && (!'${{ github.event.inputs.skip_check }}' || '${{ github.event.inputs.skip_check }}' === 'false')) {
              console.log('Cancelling ...');
              const run_id = "${{ github.run_id }}";
              await github.actions.cancelWorkflowRun({ owner, repo, run_id });
              return 'stop'
            } else {
              return 'build'
            }
          result-encoding: string

      - name: Waiting for cancellation
        run: sleep 60
        if: steps.cancel.outputs.result == 'stop'

      - name: Should build?
        run: test "${{ steps.cancel.outputs.result }}" = "build"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: pansila
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download the latest v2ray
        run: |
          wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray-linux-64.zip -d v2ray_unzip
          version=$(v2ray_unzip/v2ray --version | head -n1 | awk '{print $2}')
          if [ -z "$version" ]; then exit 1; fi
          if [[ v"$version" != "$VERSION" ]]; then exit 1; fi
          echo v2ray version: $version

      # - name: Build and push the docker image
      #   run: |
      #     docker build . -f Dockerfile.github -t pansila/v2ray_heroku:$VERSION
      #     docker image tag pansila/v2ray_heroku:$version pansila/v2ray_heroku:latest
      #     docker push pansila/v2ray_heroku:$VERSION
      #     docker push pansila/v2ray_heroku:latest

      - name: Build and push the docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.github
          context: .
          push: true
          tags: |
            pansila/v2ray_heroku:${{ env.VERSION }}
            pansila/v2ray_heroku:latest
