name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: pansila
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: download latest v2ray
        run: |
          wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray-linux-64.zip -d v2ray_unzip

      - name: build the docker image
        id: docker_build
        run: |
          version=$(v2ray_unzip/v2ray --version | head -n1 | awk '{print $2}')
          if [ -z "$version" ]; then exit 1; fi
          echo v2ray version $version
          docker build . -f Dockerfile.github -t pansila/v2ray_heroku:$version
          docker image tag pansila/v2ray_heroku:$version pansila/v2ray_heroku:latest
          docker push pansila/v2ray_heroku:$version
          docker push pansila/v2ray_heroku:latest

      - name: kick off a new heroku deploy
        run: |
          version=$(v2ray_unzip/v2ray --version | head -n1 | awk '{print $2}')
	  sudo snap install --classic heroku
	  heroku login -i <<EOF
          ${{ secrets.HEROKU_EMAIL }}
          ${{ secrets.HEROKU_PASSWORD }}
	  EOF
	  mkdir heroku_repo
	  cd heroku_repo
	  heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
	  git pull
	  echo 1 >>kick.off
	  git add kick.off
	  git commit -m "new deploy for v2ray version: $version"
	  git push heroku master

