name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: pansila
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: download latest v2ray
        run: |
          wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray-linux-64.zip
          version=$(./v2ray --version | head -n1 | awk '{print $2}')
          echo v2ray version $version

      - name: build the docker image
        run: |
          docker build . -t pansila/v2ray_heroku:$version
          docker image tag pansila/v2ray_heroku:$version pansila/v2ray_heroku:latest
          docker push pansila/v2ray_heroku:$version
          docker push pansila/v2ray_heroku:latest

