# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          curl -OJL https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray-linux-64.zip
          chmod +x v2ray
          version=$(./v2ray --version | head -n1 | awk '{print $2}')
          docker build . -t pansila/v2ray_heroku:$version
          docker tag pansila/v2ray_heroku:$version pansila/v2ray_heroku:latest
          docker login -u pansila -p ${{secrets.DOCKER_PASSWORD}}
          docker push pansila/v2ray_heroku:$version
          docker push pansila/v2ray_heroku:latest
