name: Build the docker image

on:
  push:
    branches: [ main ]
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: pansila
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: check the latest version
        continue-on-error: true
        id: check
        run: |
          github_latest=$(utils/github_get_latest_release.sh v2fly/v2ray-core)
          docker_latest=$(utils/docker_image_find_tag_equal_to_latest.sh -n pansila/v2ray_heroku -q)
          if [[ "github_latest" == "$docker_latest" ]]; then
            echo "docker image is up to date, skipping the updating"
            exit 0
          fi
          echo "docker image is out of date, current: $docker_latest, latest: $github_latest, updating..."
          echo "VERSION=$github_latest" >> $GITHUB_ENV
          exit 1

      - name: download the latest v2ray
        if: steps.check.conclusion == 'failure'
        run: |
          wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray-linux-64.zip -d v2ray_unzip
          version=$(v2ray_unzip/v2ray --version | head -n1 | awk '{print $2}')
          if [ -z "$version" ]; then exit 1; fi
          if [[ "$version" != "$VERSION" ]]; then exit 1; fi
          echo v2ray version: $version

      # - name: build and push the docker image
      #   if: steps.check.conclusion == 'failure'
      #   run: |
      #     docker build . -f Dockerfile.github -t pansila/v2ray_heroku:$VERSION
      #     docker image tag pansila/v2ray_heroku:$version pansila/v2ray_heroku:latest
      #     docker push pansila/v2ray_heroku:$VERSION
      #     docker push pansila/v2ray_heroku:latest

      - name: build and push the docker image
        if: steps.check.conclusion == 'failure'
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.github
          context: .
          push: true
          tags: |
            pansila/v2ray_heroku:${{ env.VERSION }}
            pansila/v2ray_heroku:latest
